### ISSUE TITLE
Training script for app

### ISSUE THREAD

**Issue by grofattila** [omimo/HelloTensor#2]
Hi!

I am following your tutorial ( https://omid.al/posts/2017-02-20-Tutorial-Build-Your-First-Tensorflow-Android-App.html ). 

When I try to generate the .pb file with freeze_graph I get an error.

I have all the required files in the same directory.
Any idea why I am getting this error?

Thanks in advance.

`---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-20-a920c613e02f> in <module>()
     23                           filename_tensor_name,
     24                           output_frozen_graph_name,
---> 25                           clear_devices, "")

/home/atig/GitKraken/hallgato-grofattila/Training/freeze_graph.py in freeze_graph(***failed resolving arguments***)
     80 
     81   # 'input_checkpoint' may be a prefix if we're using Saver V2 format
---> 82   if not saver_lib.checkpoint_exists(input_checkpoint):
     83     print("Input checkpoint '" + input_checkpoint + "' doesn't exist!")
     84     return -1

AttributeError: module 'tensorflow.python.training.saver' has no attribute 'checkpoint_exists'`

**Comment by omimo** [comment]
Hey,

What version of Tensorflow are you using?

**Comment by grofattila** [comment]
Hi!

tensorflow 0.10.0rc0, python 3.5  through anaconda on linux

**Comment by omimo** [comment]
The APIs have changes since. You should upgrade your tensorflow to 1.0.

**Comment by grofattila** [comment]
Upgrading to the newer tf resolved my issue.
Thanks !
